version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: example
      POSTGRES_DB: production-db
    volumes:
      - /data/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5836:5432"

volumes:
  postgres_data:
