version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: example
      POSTGRES_DB: prod-db
#    volumes:
#      - /docker/volumes/prodrest/db/data:/var/lib/postgresql/data/
    ports:
      - "5882:5432"

#volumes:
#  postgres_data: