// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: copyfrom.go

package postgres

import (
	"context"
)

// iteratorForCreateRecipeIngredients implements pgx.CopyFromSource.
type iteratorForCreateRecipeIngredients struct {
	rows                 []*CreateRecipeIngredientsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRecipeIngredients) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRecipeIngredients) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RecipeID,
		r.rows[0].ProductID,
		r.rows[0].Quantity,
	}, nil
}

func (r iteratorForCreateRecipeIngredients) Err() error {
	return nil
}

func (q *Queries) CreateRecipeIngredients(ctx context.Context, db DBTX, arg []*CreateRecipeIngredientsParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"recipe_ingredients"}, []string{"recipe_id", "product_id", "quantity"}, &iteratorForCreateRecipeIngredients{rows: arg})
}
